# Generated by Django 5.2.8 on 2025-12-05 08:34

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Monthly Toddler Tuition', 'Registration Fee 2024'", max_length=100)),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('registration', 'Registration Fee'), ('meals', 'Meals'), ('activities', 'Activities/Field Trips'), ('supplies', 'Supplies'), ('late_pickup', 'Late Pickup Fee'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fee amount in local currency', max_digits=10)),
                ('frequency', models.CharField(choices=[('one_time', 'One-Time Fee'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=15)),
                ('applies_to_class', models.CharField(choices=[('all', 'All Classes'), ('infants', 'Infants'), ('toddlers', 'Toddlers'), ('preschool', 'Preschool'), ('pre_k', 'Pre-K')], default='all', max_length=20)),
                ('description', models.TextField(blank=True, help_text='What this fee covers')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this fee structure is currently in use')),
                ('effective_date', models.DateField(help_text='Date this fee structure became/becomes effective')),
                ('end_date', models.DateField(blank=True, help_text='Date this fee structure expires (leave blank if ongoing)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fee Structures',
                'db_table': 'fee_structures',
                'ordering': ['-effective_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, help_text='Auto-generated unique invoice number', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total invoice amount', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far', max_digits=10)),
                ('issue_date', models.DateField(auto_now_add=True, help_text='Date invoice was created')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('paid_date', models.DateField(blank=True, help_text='Date invoice was fully paid', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('description', models.TextField(blank=True, help_text="What this invoice covers (e.g., 'January 2024 Tuition')")),
                ('notes', models.TextField(blank=True, help_text='Internal notes or payment terms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(help_text='Child this invoice is for', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='children.child')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance.feestructure')),
                ('parent', models.ForeignKey(help_text='Parent responsible for payment', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='children.parent')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-issue_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=10)),
                ('payment_date', models.DateField(default=datetime.date.today, help_text='Date payment was received')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('cheque', 'Cheque')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank reference, mobile money code, cheque number, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional payment notes')),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt number issued to parent', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoice')),
                ('processed_by', models.ForeignKey(help_text='Staff member who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
