# Generated by Django 5.2.8 on 2025-11-19 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, help_text='Auto-generated registration number', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(help_text="Child's date of birth")),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('medical_info', models.TextField(blank=True, help_text='Allergies, medical conditions, medications, etc.')),
                ('photo', models.ImageField(blank=True, help_text="Child's photo", null=True, upload_to='children/photos/')),
                ('is_active', models.BooleanField(default=True, help_text='Is the child currently enrolled?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'children',
                'db_table': 'children',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(help_text='Date child started/will start')),
                ('class_room', models.CharField(choices=[('toddlers', 'Toddlers (1-2 years)'), ('preschool', 'Preschool (3-4 years)'), ('pre_k', 'Pre-K (4-5 years)')], help_text='Age-appropriate classroom', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', help_text='Current enrollment status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(help_text='Child being enrolled', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='children.child')),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(help_text='Primary contact number', max_length=15)),
                ('address', models.TextField(help_text='Full residential address')),
                ('emergency_contact_name', models.CharField(help_text='Emergency contact person name', max_length=100)),
                ('emergency_contact_phone', models.CharField(help_text='Emergency contact phone number', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Linked user account for login', on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parents',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(help_text='Select all parents/guardians for this child', related_name='children', to='children.parent'),
        ),
    ]
